{
 "title": "Connector Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "{tenantId=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Files Downloaded per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(connector_downloaded_binary_count_total) by(tenantId)",
     "legendFormat": "{{tenantId}}"
    }
   ]
  },
  {
   "title": "Byte Size Transferred per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(connector_downloaded_binary_byte_size_total) by(tenantId)",
     "legendFormat": "{{tenantId}}"
    }
   ]
  },
  {
   "title": "Average download size per Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(connector_downloaded_binary_byte_size_total) by(tenantId))/(sum(connector_downloaded_binary_count_total) by(tenantId))",
     "legendFormat": "{{tenantId}}"
    }
   ]
  },
  {
   "title": "Cache Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(connector_cache_hit_count_total) by(tenantId)",
     "legendFormat": "Cache Hit Tenant: {{tenantId}}"
    },
    {
     "expr": "sum(connector_cache_miss_count_total) by(tenantId)",
     "legendFormat": "Cache Miss Tenant: {{tenantId}}"
    }
   ]
  },
  {
   "title": "Number of Connections by Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(m365_connection_count) by(tenantId)",
     "legendFormat": "{{tenantId}}"
    }
   ]
  },
  {
   "title": "Number of Tasks by Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(task_count{tenantId=~\"$tenant\"}) by(tenantId)",
     "legendFormat": "{{tenantId}}"
    }
   ]
  },
  {
   "title": "Number of Tasks by Tenant and Identity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(task_count{tenantId=~\"$tenant\"}) by(tenantId, identityId)",
     "legendFormat": "Tenant: {{tenantId}} - Identity: {{identityId}}"
    }
   ]
  }
 ]
}