{
 "title": "Consumers",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Number of consumers",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Messages total",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_published_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}) by (queue)",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_delivered_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}) by (queue)",
     "legendFormat": "published"
    }
   ]
  },
  {
   "title": "Consumers per queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue!~\"^dead-letters.*\",namespace=~\"^$namespace$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages delivered / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum ( rate(rabbitmq_queue_messages_delivered_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}