{
 "title": "CPU & Memory usage",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (container, pod)",
     "legendFormat": "pod: {{pod}} "
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (kubernetes_io_hostname, rkt_container)",
     "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container}}"
    }
   ]
  },
  {
   "title": "Total CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (kubernetes_io_hostname, rkt_container)",
     "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container}}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (container, pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, rkt_container)",
     "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container}}"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "docker: {{kubernetes_io_hostname}} | {{image}} ({{name}})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, rkt_container)",
     "legendFormat": "rkt: {{kubernetes_io_hostname}} | {{rkt_container}}"
    }
   ]
  }
 ]
}