{
 "title": "Log analysis",
 "description": "Browse, analyze logs in Elasticsearch",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "@number",
       "id": "1",
       "inlineScript": "severity:\"INFO\"",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "severity:\"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error occurances",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.labels.app.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "severity:\"ERROR\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "@number",
       "id": "1",
       "inlineScript": "severity:\"INFO\"",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "severity:\"WARN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warning occurances",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.labels.app.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "@value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "severity:\"WARN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs by severity in time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "severity.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}