{
 "title": "Jaeger Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Avg Duration per Service/Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "process.serviceName",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "operationName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "startTimeMillis", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "avg"
      }
     ],
     "timeField": "startTimeMillis"
    }
   ]
  },
  {
   "title": "Service call count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process.serviceName",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "startTimeMillis"
    }
   ]
  },
  {
   "title": "Trace duration",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "traceID",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      { "field": "select field", "id": "5", "type": "count" }
     ],
     "timeField": "startTimeMillis"
    }
   ]
  },
  {
   "title": "Operations extended stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "process.serviceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "operationName",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "meta": {
        "avg": true,
        "count": true,
        "max": true,
        "min": true,
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "timeField": "startTimeMillis"
    }
   ]
  }
 ]
}