{
 "title": "Network load",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-45m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total network traffic",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (pod_name) + sum (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Total Input traffic",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Total Output traffic",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}