{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(rabbitmq_running, node)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Currently messages in RMQ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "Messages published in total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_published_total)"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{namespace=~\"^$namespace$\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "rabbitmq_channels{namespace=~\"^$namespace$\"}",
     "legendFormat": "channels"
    },
    {
     "expr": "rabbitmq_consumers{namespace=~\"^$namespace$\"}",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Currently in queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consumers per queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_consumers{queue!~\"^dead-letters.*\",namespace=~\"^$namespace$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages delivered / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum (rate(rabbitmq_channel_messages_delivered_ack_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}[1m])) by (queue) +\nsum (rate(rabbitmq_channel_messages_delivered_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}[1m])) by (queue) +\nsum (rate(rabbitmq_channel_messages_redelivered_total{queue!~\"^dead-letters.*\", namespace=~\"^$namespace$\"}[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}