apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: haproxy/
    repoURL: https://github.com/Elinork91/helm-template
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
