apiVersion: v2
description: Rabbitmq server
name: rabbitmq
type: application
version: 0.1.0

dependencies:
  - name: rabbitmq
    version: 3.8.0
    repository: https://helmdigitalus.azurecr.io/helm/v1/repo
