apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
data:
  username: {{ .Values.global.grafana.username | b64enc }}
  password: {{ .Values.global.grafana.password | b64enc }}
type: Opaque
---
