apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  type: {{ .Values.global.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  type: {{ .Values.global.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter
  labels:
    app: prometheus-blackbox-exporter
spec:
  ports:
    - name: "9115"
      port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    app: prometheus-blackbox-exporter
  type: {{ .Values.global.serviceType }}
---
