argo-cd:
  installCRDs: false
  global:
    image:
#      tag: v2.1.3
      tag: v1.8.4



server:
  extraArgs:
    - --insecure
    - --auth-mode=sso
  config:
    repositories: |
      - type: helm
        name: stable
        url: https://charts.helm.sh/stable
      - type: helm
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
    dex.config: |
              staticClients:
              - id: argo-workflows-sso
                name: Argo Workflow
                redirectURIs:
                  - https://argo-workflows.mydomain.com/oauth2/callback
                secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
    sso:
        issuer: https://argo-cd.mydomain.com/api/dex
        # sessionExpiry defines how long your login is valid for in hours. (optional, default: 10h)
        sessionExpiry: 240h
        clientId:
          name: argo-workflows-sso
          key: client-id
        clientSecret:
          name: argo-workflows-sso
          key: client-secret
        redirectUrl: https://argo-workflows.mydomain.com/oauth2/callback
dex:
  image:
    tag: v2.23.0
  env:
    - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: argo-workflows-sso
          key: client-secret