argo-cd:
  installCRDs: false
  global:
    image:
#      tag: v2.1.3
      tag: v1.8.4
  dex:
    enabled: true
    connectors:
    - config:
        clientID: system:serviceaccount:argocd:argocd-dex-server
        clientSecret: <secret>
        insecureCA: true
      id: openshift
      name: OpenShift
      type: openshift

  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm