appArgocd:
  gitRevision: "HEAD" #-> alpha | beta | rc | final | vX.X.X
  hostDomain: {}
  sourceRepo: "https://github.com/Elinork91/helm-template"
  destinationServer: https://kubernetes.default.svc
  projectName: "default"

monitoring:
  enableDeploy: true
  grafana:
    username: "ARGO_GRAFANA_USERNAME"
    password: "ARGO_GRAFANA_PASSWORD"
    userSignup: 'false'
    anonymousAccess: 'false'
    ingress:
      enabled: 'true'
    deployment:
      imagePullSecretsName: "docker.io"
  prometheusBlackbox:
    deployment:
      imagePullSecretsName: "docker.io"

global:
  syncPolicy:
    {}