{{- if .Values.kong.enabled }}
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: kong-services-configmap
  labels:
    app: kong-services-configmap
data:
  kong.yaml: |-
{{ tpl (.Files.Get "files/config/kong.dbless.yaml" | indent 4) . }}
{{- end }}
