{{- if .Values.kong.enabled }}
---
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: kong-configmap
  labels:
    app: kong-configmap
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yaml"
  KONG_MEM_CACHE_SIZE: "{{ .Values.kong.memCacheSize }}"
  KONG_NGINX_WORKER_PROCESSES: "{{ .Values.kong.workers }}"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
{{- end }}
