---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-idp-{{ .Values.configuration.realm }}
data:
  config.yaml: |-
    default:
      keycloak:
        protocol: {{ .Values.configuration.protocol | default "http"}}
        host: {{ .Values.configuration.host | default "localhost"}}
        port: {{ .Values.configuration.port | default "8080"}}
        path: {{ .Values.configuration.path | default "/auth"}}
        realm: {{ .Values.configuration.realm | default "kmrealm"}}
        masterRealm: {{ .Values.configuration.masterRealm | default "master"}}
        {{- with .Values.configuration.identityProviders}}
        identityProviders:
        {{- toYaml . | nindent 8}}
        {{- end}}
      {{- with .Values.configuration.retry}}
      retry:
        delay: {{ .delay | default "1000" | int }}
        count: {{ .count | default "10" | int }}
      {{- end}}
