apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-idp-config-{{ .Values.configuration.realm }}
spec:
  template:
    spec:
      {{- with .Values.configuration.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.configuration.realm }}-init
          image: {{ .Values.configuration.image.repository | default "verosteam/keycloak-idp-setup" }}:{{ .Values.configuration.image.tag | default .Chart.AppVersion }}
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
      restartPolicy: OnFailure