{{- $values := . -}}
{{- range .Values.users }}
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: {{ .name }}
  labels:
  {{- include "du-identity-manager.labels" $values | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      realm: {{ .realm }}
    {{- include "du-identity-manager.selectorLabels" $values | nindent 6 }}
  user:
    {{- .user | toYaml | nindent 3 }}
---
{{- end}}
