apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql-secret-db
data:
  username: {{  .Values.db.username  | b64enc }}
  password: {{  .Values.db.password  | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
data:
  POSTGRES_DATABASE: {{ .Values.db.name | b64enc }}
  POSTGRES_HOST: {{ .Values.db.host | b64enc }}
  POSTGRES_SUPERUSER: "true"
  POSTGRES_USERNAME: {{ .Values.db.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  POSTGRES_EXTERNAL_PORT: "5432"
  POSTGRES_EXTERNAL_ADDRESS: {{ .Values.db.host | b64enc }}

type: Opaque
